### ISSUE TITLE
Enquiry regarding the license status of the images in your dataset

### ISSUE THREAD

**Issue by layilpaht** [yuhonas/free-exercise-db#12]
Hi,
Thanks for the dataset. I am planning on working on a fitness app & this dataset will contribute a lot in that regards. Thanks again

However I was having a very important doubt regarding the license status of the images in your dataset.
Are the images in your dataset available without any copyright issue/open sourced & can be used in a commercial app without any issues later on?

Thanks & Regards

**Comment by yuhonas** [comment]
Hey, no problems at all! glad it was helpful to you, in regards to image licensing it has come up before see https://github.com/yuhonas/free-exercise-db/issues/2 I _still_ need to add that to the README, I hope that answers your question

Best of luck

**Comment by layilpaht** [comment]
Thanks a lot for the reply !!!
