### ISSUE TITLE
License of Images?

### ISSUE THREAD

**Issue by FKLC** [yuhonas/free-exercise-db#2]
Hello,

I was wondering where you got the images from. I want to use your database, but I'm not sure if the images are royalty free, so I wanted to ask about it.

Thank you!

**Comment by yuhonas** [comment]
Hi, a great question!, this project is a fork/reworking of [exercises.json](https://github.com/wrkout/exercises.json) inspired by [this issue](https://github.com/wrkout/exercises.json/issues/5) the derived project is licensed using [Unlicense license](https://github.com/wrkout/exercises.json/blob/master/LICENSE.md) though I actually have no idea where the images are from or if they are royalty free so usage would be at your own risk (i will update the README to make this clearer) 

Ideally i'd love some known royalty free imagery, perhaps even via generative AI but i'm not sure if it's quite there yet

**Comment by FKLC** [comment]
I see. Thank you for answering!

**Comment by skyerus** [comment]
It seems that the images aren't royalty free sadly: https://github.com/wrkout/exercises.json/issues/305
