### ISSUE TITLE
Alternate names for exercises

### ISSUE THREAD

**Issue by IgnisDa** [yuhonas/free-exercise-db#3]
Thanks for this really helpful project!

I am trying to port a workout dump that uses exercises from [ExerciseDB](https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb/). Since most of the exercises have a different name here, it is quite difficult to do so. I suggest we add a new key to each exercise called `alternateNames: string[]`. This will allow others users to port their own data to this dataset more easily.

I can make a PR for the same.

**Comment by yuhonas** [comment]
Hey, glad it's been helpful! sounds totally reasonable, My hope was that we could use a single canonical name but in the real world that's probably a little too much to ask for 😆 out of interest have you got some examples?

**Comment by IgnisDa** [comment]
I have added link to a dataset above, most exercises have a different name as to what this database has.

**Comment by yuhonas** [comment]
I see, happy for you to push up a PR!

**Comment by IgnisDa** [comment]
Hello. Sorry, I never was able to do it since it was taking too much effort. However, since then, I have created a mapping of around 200 exercises from exerciseDb to this project for my own [project](https://github.com/ignisda/ryot).

I have written down some instructions [here](https://gist.github.com/IgnisDa/c21c28dd83571ca07f1a7a824b5e8139?permalink_comment_id=4725066#gistcomment-4725066). Maybe it will be helpful to someone!
