### ISSUE TITLE
[Suggestion]: Add field for type of exercise

### ISSUE THREAD

**Issue by IgnisDa** [yuhonas/free-exercise-db#7]
While working on [Ryot](https://github.com/ignisda/ryot), I needed to classify each exercise into one of the following: `Duration`, `DistanceAndDuration` and `RepsAndWeight`. [Here](https://github.com/IgnisDa/ryot/blob/f36f967b6765493763e0d7287932e3ed8e23cf37/apps/backend/src/fitness/resolver.rs#L554-L563) is the code I am using to classify each exercise for now.

However, I think there should be an additional type: `RepsOnly`. For example, Pushups, Pullups, Crunches and so on.

Would you be open to adding a new field `type` to the schema, which will be an enum with 4 variants? This should be not be very difficult since I already have 3 variants sorted out. WIll have to do the `RepsOnly` variant manually.

**Comment by IgnisDa** [comment]
I am open to making a PR for this.

**Comment by yuhonas** [comment]
Hey @IgnisDa sounds reasonable! 

Happy for you to open a PR, glad the project has been useful to you

**Comment by yuhonas** [comment]
Closing this one out as it's looking stale feel free to re-open
